name: Build AAB

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build AAB (No wrapper needed)
        run: |
          wget https://services.gradle.org/distributions/gradle-8.4-bin.zip
          unzip gradle-8.4-bin.zip
          ./gradle-8.4/bin/gradle bundleRelease
